### ISSUE TITLE
Where is the list of valid CSVs for import?

### ISSUE THREAD

**Issue by MaitlandMarshallMEX** [pelias/openaddresses#161]
I tried importing au-countrywide.csv from https://openaddresses.io/ without any luck. I noticed through browsing the code of the vagrant project, you host some files here: http://data.openaddresses.io.s3.amazonaws.com/

I was able to download files such as au-queensland.zip and through the naming syntax find other Australian states to download.

Can you please update the documentation and provide a list of valid downloads? The documentation basically says you can use the files from openaddresses.io, but none that I have tried have worked. Only the ones you host (for Australia).

**Comment by orangejulius** [comment]
Hey @MaitlandMarshallMEX,
First, just to clarify, Pelias (the geocoder) and OpenAdresses (the aggregation of authoritative address datasets) are separate projects. So, we probably won't be providing a list of valid downloads, since the OpenAddresses project [already does that](https://results.openaddresses.io/) (you probably saw this page already).

The reason you ran into trouble, probably, is that our vagrant image is rather unmaintained right now, and I know some of the code for downloading OpenAddresses data doesn't work very well. We're not really certain of the future of the Vagrant image, so it may not be fixed. Fortunately, there's not very much involved in setting up the pelias-openaddresess importer directly. All it does is read a few CSV files after all.

The [configuration](https://github.com/pelias/openaddresses#configuration) section of the documentation for the importer, which you've probably already seen, details how to set it up. Basically there's a `pelias.json` file which handles all the configuration (in the vagrant image i think it's at `/etc/pelias/pelias.json` or something similar). The easiest thing to do is make the `files` value an empty array, and then put any CSVs you care about within the `datapath` directory. Then you can switch over to the actual importer code directory (i think all the importers live in `/opt/pelias`) and run `npm start`. It should pick them all up.

You also might have more luck with our full [installation docs](https://github.com/pelias/pelias-doc/blob/master/installing.md) that tell you how to set up Pelias from scratch, and _ARE_ kept very up to date. 

We have a [Gitter](https://gitter.im/pelias/pelias) chat room if you want to ask more detailed questions as you go along, or of course feel free to ask more questions here. Hope that helps!

**Comment by MaitlandMarshallMEX** [comment]
Thanks @orangejulius!

I was able to get a full installation done through those docs - thank you heaps. It is an awesome project.

I do have one more question, how do you go about updating the data? I noticed with vagrant provision it reinstalls everything and reimports the data. I can do this with the cURL -XDELETE "etc:9200/pelias" and run through all the import pipelines again. Is this what you would recommend? Or would it be better to setup deduplicator and just run the imports again?

I finished a full import of Australia only to realise I never had adminLookup set to true, so I have to start again?

**Comment by orangejulius** [comment]
That's right, unfortunately thee best way to update data is to delete everything and completely reindex. Make sure you use the `schema` repo to correctly set up the mappings in ES again after the `curl -XDELETE`. (we forget this a lot and without the mappings, no queries work but the import will proceed, and a bunch of time is wasted).

Elasticsearch _does_ have recently added [facilities for reindexing](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html), and we do someday want to support [minutely updates](https://github.com/pelias/openstreetmap/issues/26), especially for OSM, so hopefully someday we'll have a better answer.

Until then, just reindex. In our production instance for Mapzen Search we use [Elasticsearch aliases](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) to swap out new builds without any downtime. If that's something that you're interested in I can share some of how it works. It's not very tricky and has worked surprisingly well.

Glad you're liking pelias, please let us know if you have any other suggestions or questions!

**Comment by MaitlandMarshallMEX** [comment]
Fantastic, thanks for your help!

In order to speed up the imports, can I run two at the same time? For example, running the OSM import alongside the OA import or would this cause issues?

**Comment by dianashk** [comment]
Running importers alongside each other is definitely the way to go. We typically run 2 at a time as well. Keep in mind that will require a machine with a significant amount of memory to accommodate 2 instances of the admin-lookup data, or 2 different machines pushing records to a common Elasticsearch instance.

Best of luck and let us know how it goes. :tada: :computer:
