### ISSUE TITLE
City and region information being dropped

### ISSUE THREAD

**Issue by rowanwins** [pelias/openaddresses#165]
Gday all,

Thanks so much for the hard work on Pelias and it's associated pieces. 

I've just imported the Australian Countrywide dataset into my pelias instance. When I open the csv from OpenAddresses I can see City and Region columns that are populated with useful info. However it looks like this information then gets dropped when I import it into pelias. 

It looks like the hosted Mapzen search instance relies on this information coming from WhosOnFirst.

Is there anything that I can set anywhere to help retain this information and map it to the relevant pelias fields for import rather than relying on WhosOnFirst?

Thanks,
Rowan

**Comment by rowanwins** [comment]
Hmm digging into the source code a bit further it looks like these [lines could possibly be relevant](https://github.com/pelias/openaddresses/blob/master/lib/streams/documentStream.js#L20-L32)...

**Comment by orangejulius** [comment]
Hey @rowanwins,
At the moment, we don't support using the city and region columns from OA, but this is a [hotly debated topic](https://github.com/pelias/pelias/issues/389), and is frequently something that is asked about, especially for OpenStreetMap.

In general, OSM and OpenAddresses don't have very consistent data for any admin data, hence why we prefer to use Who's on First, but the downside to consistency is that some totally valid data is thrown away. The admin data in OSM is pretty complicated, so we're pretty sure it's best to just stick with Who's on First. For OpenAddresses though, it's quite easy to access, and you already found the relatively straightforward section of code that reads the data and adds it to our documents.

I think we would gladly merge a pull request that adds the ability to use those two columns, if it was set up so that setting the [adminLookup flag](https://github.com/pelias/config/blob/master/config/defaults.json#L59) to true disabled it, and used the Who's on First data in exactly the same way as it does now with no change in behavior. Unit tests would definitely help too.

[Here's](https://github.com/pelias/whosonfirst/blob/master/src/peliasDocGenerators.js#L48-L58) some corresponding, but more complicated code from the Who's on First importer that handles admin info. It might be useful for figuring out the right way to set that data. Of course you're welcome to ask questions here or in our [Gitter chat](https://gitter.im/pelias/pelias) along the way if you decided to try your hand at this.

**Comment by rowanwins** [comment]
Gday @orangejulius 

Thanks for your response, again thanks for all your great work on pelias. I'm sure when you start out it all seems like it shouldn't be too hard however once you get into the weeds sifting through the data it all becomes incredibly complex. 

I'll attempt to do a bit more digging into the Open Addresses data to get myself a bit more familiar with it but my impression was that they were attempting to provide some sort of standardisation so that it should be much more consistent that something like OSM.

What I could perhaps see is some additional config determining whether you use the OA Admin Boundaries, what I'm not sure of is whether this is required setting for each potential OA data file to cater for variability in the those files. In this scenario people could then fall back to the WOF admin lookup if OA does not contain suitable info.  So a config example might look something like
````
   'openaddresses': {
    'index_data': true,
    "adminLookup": true,
    'data_files': [
      {
         filename: 'us-ny-nyc',
         useAdminBoundaryFields: true 
      },
      {
         filename: 'at-city_of_vienna',
         useAdminBoundaryFields: false
      }
    ]
  }
```
In this example everything would get assigned admin boundaries, in the case of NYC they'd come from the source data in OA, and in the case of Vienna they'd be derived from WOF.

And another quirk I noticed was that OA imported data doesn't set a country, and there is nothing in the source csv that specifies a country. I wonder if we could derive that based on the ISO country code in the filename? 

As a more general comment it kind of feels like at the moment I'm pretty much forced into using WOF to make Pelias usable which is kind of ok however it's just another layer that people are then required to understand, hopefully if we could get more of the source data in then we'd be less reliant on WOF.

Anyway will start taking a bit of a look and will see what I can come up with

Cheers

**Comment by dianashk** [comment]
Hey @rowanwins, I think that's probably the best approach: make it configurable and tell the importer which admin hierarchy to prefer. So WOF will always be available as a default when other data isn't there. As far as our hosted instance, Mapzen Search, is concerned, we will probably always use WOF and disregard source admin hierarchy because we want to normalize the data from all the different sources we import. However, if a user is running a local instance with only OA, for example, they might want to keep the source admin data when it's available.

Since we won't be touching this code for some time, it's a great place to contribute, so if you  make changes please push them our way. Also as you're designing or implementing we are happy to chat about your ideas or look at some preliminary code.

Cheers! :tada:
