### ISSUE TITLE
Elasticsearch errors when doing the import on a local machine

### ISSUE THREAD

**Issue by sergiyprotsiv** [pelias/openaddresses#328]
Hi, I'm attempting a worldwide import on a local machine, but have persistent Elasticsearch errors, with ES dropping connections resulting in batch_error and missing data. The typical example is as follows:

> Elasticsearch WARNING: 2017-12-11T14:05:12Z
  Unable to revive connection: http://localhost:9200/
> Elasticsearch WARNING: 2017-12-11T14:05:12Z
  No living connections
> 2017-12-11T14:05:12.121Z - error: [dbclient] esclient error Error: No Living connections
    at sendReqWithConnection (/mnt/scratch/pelias/openstreetmap/node_modules/elasticsearch/src/lib/transport.js:225:15)
    at next (/mnt/scratch/pelias/openstreetmap/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
> 2017-12-11T14:05:12.121Z - error: [dbclient] invalid resp from es bulk index operation
> 2017-12-11T14:05:12.121Z - info: [dbclient] retrying batch [500]
> 2017-12-11T14:05:13.643Z - info: [dbclient]  paused=true, transient=15, current_length=0, indexed=3754500, batch_ok=7509, batch_retries=0, failed_records=0, venue=1578642, address=2175858, persec=0, batch_error=35

The errors happen reliably and within an hour when running multiple importers in parallel. Running sequentially, Geonames and WOF have imported without issues. OA and OSM start throwing errors after a few hours of importing (e.g. after about 600M OSM nodes in the above example, after getting through half of Brazil in OA).

The hardware is quite powerful (32 cores, 128 GB RAM, though not SSDs - HDD in RAID0), so I do not believe this is an issue. ES maxes out 2-3 cores during import, but then it suddenly requires more power and starts dropping connections. 

Not an expert in ES (this is my first encounter), but maybe there is some reindexing going on, or maybe even heavy garbage collection. I give ES 30GB memory (via `ES_JAVA_OPTS="-Xms30g -Xmx30g"`) and run it by launching a daemon. ES version is 2.4, the system is Ubuntu 16.04. I tried with both standard settings and with some suggestions found on the web. The ES documentation is missing and seems to be very different across versions with people suggesting undocumented parameters to tweak. The config that worked to import Geonames and WOF is `
threadpool.bulk.type: fixed
threadpool.bulk.size: 25
threadpool.bulk.queue_size: 1000
`

I imagine that there could be some ES setting to either give it more resources, keep retrying for longer (or ideally just wait more between retries), or maybe changing batch sizes? Alternatively, is there a way to throttle the importers to a given maximum inserts per second?

**Comment by orangejulius** [comment]
Hey @sergiyprotsiv,
Thanks for reporting this. We've seen it sporadically in our build environments as well. I believe it ultimately comes down to some bad behavior in [pelias/dbclient](https://github.com/pelias/dbclient): it has retries to handle when a single batch import request fails, but it is sent at the same time as other requests, and effectively leads to an increase in the load on Elasticsearch. If the retry was already because of load, it actually makes things worse.

We've wanted to change it for a long time, but the code in dbclient is very hard to modify. It was written a long time ago before we new much about the Node.js stream interface. It could probably be re-written with [through2](https://github.com/rvagg/through2) in 10% of the code. We may get to that soon as we're trying to decrease the resources required for imports, but if it happens to be something you want to work on, let us know and we can help you get started.

In the interim, the one tweakable parameter in that module is to change how many records are indexed in a single batch. The default is a potentially too large 500. [This branch](https://github.com/pelias/openaddresses/tree/change-batch-size) that I just created in the OA repo is (I think) an example of how it can be change. If you'd like to test out that branch or something like it and report back, that would be much appreciated!

**Comment by sergiyprotsiv** [comment]
Hi @orangejulius, I tried to run the import with the changes you propose, and it is indeed more stable (though about 2-3 times slower). In the end, however, it lost the connection anyway after about 60M addresses imported. Tried with a subset of most relevant countries for me and it imported 10M addresses without any errors.
A couple of questions: 
- does it make sense to import OA data in parts (e.g. import Austria, snapshot if successful, otherwise revert back, etc) or is there some sort of finalization script that runs once the OA import is done
- what would be the corresponding change (i.e. batch size 100) for the OSM importer, I tried to figure it out, but the structure of the importer is different enough for me to not succeed.
Thanks.

**Comment by orangejulius** [comment]
Hey @sergiyprotsiv,
Thanks for being patient for my response. As you might know [a lot has happend in the meantime](https://mapzen.com/blog/shutdown/).

A full planet snapshot takes around an hour to make, so incrementally building up to that size snapshot would slow things down and require lots of intermediate storage. That said, it would definitely work. There is not any sort of finalization script with Pelias, so as soon as data is sent to Elasticsearch it's ready to be queried against, which is nice. I don't recommend it though.

[Here's](https://github.com/pelias/openstreetmap/tree/smaller_batch_size) the same change for the OSM importer.

In the past, the we haven't really though much about this sort of issue, since we had the resources of Mapzen and could easily just launch another Elasticsearch instance if our imports started failing. Now we'll have to be a little more judicious with server usage, which actually probably helps as most people in the community will be using smaller clusters as well.

Like I mentioned before we need to spend some time refactoring or possibly completely rewriting the [pelias/dbclient](https://github.com/pelias/dbclient) module. It could definitely become quite smart about intelligently retrying batches or even resizing them based on the latency and error codes coming back from Elasticsearch.

**Comment by orangejulius** [comment]
Hey @sergiyprotsiv,
I think I've made some progress with this issue. Your comment that it was related to the Elasticsearch threadpool was probably right. Our importers were allowing a high number of concurrent requests which was probably overwhelming the default bulk index queue (of only 50). I've tried changing it to a more reasonable value. If you have a second, can you try [this OA importer branch](https://github.com/pelias/openaddresses/tree/test-new-dbclient)?

**Comment by sergiyprotsiv** [comment]
Hey @orangejulius, thanks a lot for getting back and apologies for the delay. 

I had another try to run Pelias locally and realized that for now I cannot reason at all about the performance of Elasticsearch. The strangest example is that starting up the PiP service with full WOF data takes either about 40 seconds or about 5000 seconds (with about 70% probability of the latter). The actual geocoding then (with a full WOF database and OSM/OA for Scandinavia) takes about 0.5 seconds per address, so would take me a few months to geocode my data.

This is not directly related to the issue I started with, of course. Just wanted to let you know that for now I'm not gonna test the performance in the short term since I think there are issues with my setup that are unrelated to Pelias and I cannot invest enough time to understand ES deeper than I do now.

**Comment by orangejulius** [comment]
Ouch @sergiyprotsiv, that is not the performance we usually see with Pelias. The PiP service _has_ been observed to load that slowly on small AWS EBS which have "burst" performance. If thats the case for you let us know and we can help you fix it. In fact if you want to run any aspect of your setup by us for performance considerations, we might be able to help.

**Comment by sergiyprotsiv** [comment]
Hey @orangejulius, I never really got to testing this again, did this manually in Postgres instead. Feel free to close the issue. Thanks for your help!
